---
name: kmdr-parser
summary: A parser/validator for kmdr specs in YAML or JSON format
link: https://github.com/ediardo/kmdr-parser
locale: en
options:
  - long: ["--show-stats"]
    short: ["-s"]
    summary: Show total number subcommands and options in a schema
  - long: ["--help"]
    short: ["-h"]
    summary: output usage information
  - long: ["--version"]
    short: ["-v"]
    summary: output the current version
